development:
  adapter: postgresql

test:
  adapter: postgresql
  #adapter: async

production:
  adapter: postgresql
  #adapter: redis
  #url: redis://localhost:6379/1
  #channel_prefix: monsoon_dashboard_production
