access_profiles:
  "xs:internet":
    "keppel_account_pull:$1":
      display_name: "Keppel Account Pull"
      description: Pull access for keppel account
      $1: Keppel account name
    "keppel_account_push:$1":
      display_name: "Keppel Account Push"
      description: Push and pull access for keppel account
      $1: Keppel account name
    "dns_reader":
      display_name: "DNS Reader"
      description: Allow read access to the designate API
    "dns_edit_zone:$1":
      display_name: "DNS Edit Zone"
      description: Edit records of dns zone
      $1: Zone ID
