/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowRouteImport } from './routes/show'
import { Route as IndexRouteImport } from './routes/index'

const ShowRoute = ShowRouteImport.update({
  id: '/show',
  path: '/show',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/show': typeof ShowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/show': typeof ShowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/show': typeof ShowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/show'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/show'
  id: '__root__' | '/' | '/show'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShowRoute: typeof ShowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/show': {
      id: '/show'
      path: '/show'
      fullPath: '/show'
      preLoaderRoute: typeof ShowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShowRoute: ShowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
