# This config is used to control the visibility of plugins in the navigation, 
# to define floating ip networks.
# The first config is the default config, which is used if no other config matches
# all following configs are used to match specific domains.
domains:
  # the first config is the default config, which is used if no other config matches
  # all following configs are used to match specific domains.
  - name: any domain 
    regex: ".*"
    floating_ip_networks:
      - "FloatingIP-external-%DOMAIN_NAME%-05"
      - "FloatingIP-external-%DOMAIN_NAME%-04"
      - "FloatingIP-external-%DOMAIN_NAME%-03"
      - "FloatingIP-external-%DOMAIN_NAME%-02"
      - "FloatingIP-external-%DOMAIN_NAME%-01"
      - "FloatingIP-external-%DOMAIN_NAME%"
      - "Converged Cloud External"    
    dns_c_subdomain: true   

  - name: iaas
    regex: "^iaas-.*$"
    disabled_plugins:
      - automation
      - reports
      - masterdata_cockpit
    floating_ip_networks:
      -  FloatingIP-external-iaas-01  
    dns_c_subdomain: false  