# this config is used to control the visibility of plugins in the navigation, 
# to define floating ip networks.
domains:
  - name: test
    regex: "__test__"
    disabled_plugins:
      # following plugins name should be the same as the plugin name in the plugins directory
      - test-plugin
