# this config is used to control the visibility of plugins in the navigation,
# to define floating ip networks.
domains:
  # Most general pattern last
  - name: any domain
    regex: ".*"
    floating_ip_networks:
      - "FloatingIP-external-%DOMAIN_NAME%-07"
      - "FloatingIP-external-%DOMAIN_NAME%-06"
      - "FloatingIP-external-%DOMAIN_NAME%-05"
      - "FloatingIP-external-%DOMAIN_NAME%-04"
      - "FloatingIP-external-%DOMAIN_NAME%-03"
      - "FloatingIP-external-%DOMAIN_NAME%-02"
      - "FloatingIP-external-%DOMAIN_NAME%-01"
      - "FloatingIP-external-%DOMAIN_NAME%"
      - "Converged Cloud External"
    disabled_dns_provider:
      - "Internal SOV Hosted Zone"
    dns_c_subdomain: true
    check_cidr_range: true
    terms_of_use_name: "actual_terms"

  # More general pattern
  - name: marioworld
    regex: "^marioworld-.*$"
    disabled_plugins:
      - automation
      - reports
      - masterdata_cockpit
      - webconsole
      - dns_service
      - email_service
    disabled_features:
      - documentation
      - support
      - domain_switcher
      - internal_help_links
      - terms_of_use
      - networking_backup
      - public_images
    terms_of_use_name: "marioworld_terms"
    floating_ip_networks:
      - FloatingIP-external-marioworld-01
    dns_c_subdomain: false
    check_cidr_range: false
    federation: true
    idp: "https://mario.world.corp"

  # Most specific first
  - name: marioworld-and-luigi
    regex: "^marioworld-and-luigi.*$"
    idp: "https://marioworld-and-luigi.world.corp"
