# this config is used to control the visibility of plugins in the navigation,
# to define floating ip networks.
domains:
  - name: test
    regex: "_test_"
    disabled_features:
      - documentation
      - support
      - domain_switcher
      - internal_help_links
      - terms_of_use
      - networking_backup
    terms_of_use_name: "test_domain_terms" # this term needs to be added to config/settings.yaml
    disabled_plugins:
      # following plugins name should be the same as the plugin name in the plugins directory
      - test-plugin
    floating_ip_networks:
      - "test_05"
      - "test_04"
      - "test_03"
      - "test_02"
      - "test_01"
    dns_c_subdomain: false
    # set this to use the federation feature in keystone
    federation: false
