# this config is used to control the visibility of plugins in the navigation,
# to define floating ip networks.
domains:
  - name: iaas
    regex: "^iaas-.*$"
    disabled_plugins:
      - automation
      - reports
      - masterdata_cockpit
      - webconsole
    disabled_features:
      - documentation
      - support
      - domain_switcher
    floating_ip_networks:
      - FloatingIP-external-iaas-01
    dns_c_subdomain: false
    check_cidr_range: false
