/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EntriesIndexRouteImport } from './routes/entries/index'

const EntriesIndexRoute = EntriesIndexRouteImport.update({
  id: '/entries/',
  path: '/entries/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/entries': typeof EntriesIndexRoute
}
export interface FileRoutesByTo {
  '/entries': typeof EntriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/entries/': typeof EntriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/entries'
  fileRoutesByTo: FileRoutesByTo
  to: '/entries'
  id: '__root__' | '/entries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  EntriesIndexRoute: typeof EntriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/entries/': {
      id: '/entries/'
      path: '/entries'
      fullPath: '/entries'
      preLoaderRoute: typeof EntriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  EntriesIndexRoute: EntriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
